### ISSUE TITLE
Halloween Moos

### ISSUE THREAD

**Issue by grayggr** [RicardoTheCoder/MiniMoos#19]
- [x] I am using a release version of the mod
- [x] I have mods that integrate with this installed:
     - [x] Tinker's Construct
     - [x] Mine Factory Reloaded
     - [x] Mine Addons
     - [x] Moo Fluids
     - [x] Waila
     - [x] Avaritia
- [x] I also have other mods installed
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## Additional Information
- [ ] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [ ] Java 8
- [ ] Minecraft Version:
     - [x] 1.10.2

I am playing the release version of the mod within Foolcraft 2.

I have tried disabling halloween cows through the config but they still spawn.

  Should Halloween Moos appear? [Default: true]
    B:HalloweenMoo=false

   Should Halloween Moos spawn all year? (Their spawn rate is lower outside halloween) [Default: true]
    B:HalloweenMoosSpawnAllYear=false

in a new world if a spawn near to them they absolutely wreck me!

**Comment by IRicTheCoder** [comment]
@grayggr This as been already solved in this issue scalda/FoolCraft#828. This is not an issue from mini moos it is because Moo Fluids was not removed yet in favor of Mini Moos. It was still there so it would convert Moo Fluid's Cows into Mini Moo's Cows, this is not needed anymore and the mod can be removed.

To fix your problem you can reactivate the HalloweenMoos and just remove Moo Fluids.

**NOTE:** No cow added by mini moo attacks, they counter your attack but they won't chance you or attack you directly, and all cows added by mini moos are mini cows, anything outside those bounds needs to be from another mod, in this case from Moo Fluids.

**Comment by grayggr** [comment]
Thanks
