### ISSUE TITLE
Crash when in RFTools Dimension

### ISSUE THREAD

**Issue by RatchetG95** [RicardoTheCoder/MiniMoos#23]
- [X] I am using a release version of the mod
- [X] I have mods that integrate with this installed:
     - [X] Tinker's Construct
     - [X] Mine Factory Reloaded
     - [X] Mine Addons
     - [X] Moo Fluids
     - [X] Waila
     - [X] Avaritia
- [X] I also have other mods installed
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report(s)

## Additional Information
- [X] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [X] Java 8
- [X] Minecraft Version:
     - [X] 1.10.2

## Issue Description

I am playing i Foolcraft 2.4 and have added Draconic Evolution, RFTools Dimensions, Environmental Tech (All are using the latest version available in the twitch app) and OptiFine 1.10.2_HD_U_E3

I have created two rftools dimensions, one seems fine but when i go to the other one the world crashes randomly (i can stay there for 5 seconds or 5 mins befor the world crashes), i tired updating the mini moos mop to version 1.4 but the problem persisted, also tried updating McJtyLib to 1.1x-2.4.5 but it still crashes.

## Reproduce Steps

Go into the dimension and wait for a bit.

## Additional Information

Crash Report:
https://pastebin.com/mT9iGc2p

Thanks in advance

**Comment by IRicTheCoder** [comment]
@RatchetG95 Updating McJtyLib makes no effect in anything, that lib as nothing to do with my mod. The lib I use is YetAnotherCore.

The problem is because the mod isn't recognizing the type of the dimension you are in, in this exact moment I can't fix it but as soon as I can I will upload a version with that fixed and should work fine with all dimensions, however, the moos that will appear might be the same as the ones from the overworld. Gonna check to see if I can make this more accurate.

**Comment by RatchetG95** [comment]
Thanks for the quick response, if you need anythig else just ask.

**Comment by IRicTheCoder** [comment]
@RatchetG95 I just uploaded a new version 1.4.1 that should fix the issue you are having. Should be available shortly.

**Comment by RatchetG95** [comment]
Updated the mod and everything seems to be working just fine. Thanks.
